### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by jboelaert** [elbamos/largeVis#13]
Hi, thanks a lot for making this package.
I have trouble installing it, however. I'm running R 3.3.0 on a Debian 8, and all dependencies are satisfied. This is what I get :

`$ R CMD INSTALL largeVis`
`* installing to library ‘/home/bart/R/x86_64-pc-linux-gnu-library/3.3’`
`* installing *source* package ‘largeVis’ ...`
`** libs`
`g++ -std=c++11 -I/usr/share/R/include -DNDEBUG   -I"/home/bart/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include" -I"/home/bart/R/x86_64-pc-linux-gnu-library/3.3/RcppProgress/include" -I"/usr/lib/R/site-library/RcppArmadillo/include"  -fopenmp -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c largeVis.cpp -o largeVis.o`
`largeVis.cpp: In function ‘void checkVector(const vec&, const string&)’:`
`largeVis.cpp:25:9: error: ‘const vec’ has no member named ‘has_nan’`
`if (x.has_nan() || x.has_inf())`
`^`
`largeVis.cpp:25:24: error: ‘const vec’ has no member named ‘has_inf’`
`if (x.has_nan() || x.has_inf())`
`^`
`/usr/lib/R/etc/Makeconf:141: recipe for target 'largeVis.o' failed`
`make: *** [largeVis.o] Error 1`
`ERROR: compilation failed for package ‘largeVis’`
`* removing ‘/home/bart/R/x86_64-pc-linux-gnu-library/3.3/largeVis’`

**Comment by elbamos** [comment]
That's odd, but anyway I expect to push a major update in a few days so check back and we'll see if that fixes it.

**Comment by DataWaveAnalytics** [comment]
Hello,
First, thanks @elbamos for this code.
Just curiosity @elbamos , what are you including in the next push?

Cheers
