### ISSUE TITLE
Any plans for Pythong bindings?

### ISSUE THREAD

**Issue by FuriouslyCurious** [elbamos/largeVis#16]
Thank you for implementing LargeVis - I am eager to try the algo since paper was published.

Do you have any plans to add Python bindings for it?  Thanks again.

**Comment by elbamos** [comment]
Thanks!  I'm not planning on Python because  the reference implementation includes a python binding. You can see that in @lferry007 's repo. 

If you use the R version, I suggest using the one in branch 0.1.7, which hopefully will become the master tonight.
