### ISSUE TITLE
There's no explicit working code in the repo to test the plotting.

### ISSUE THREAD

**Issue by davidleon** [elbamos/largeVis#3]
It's better to integrate the mnist example.

**Comment by elbamos** [comment]
Can you clarify what you're looking for in particular?  If you want to reproduce the mnist plot I have up, I'm happy to share the data, but its a big file, so I'll have to give it to you by dropbox or something else.

**Comment by davidleon** [comment]
yes, the mnist plot. But i don't need the data. I would like the code actually.

**Comment by davidleon** [comment]
it's great to see one plotting implementation. how about the colorized one. and how do you guys deal with the mnist data? which package used? and how to visualize the iris data? new to R.

**Comment by elbamos** [comment]
David, the complete code for the mnist example is in the file README.Rmd.  

(Also, there isn't an "us guys."  This is my implementation of the algorithm presented in the paper, I'm not an author of the paper.  I did correspond with the authors, who very generously provided additional details concerning their implementation and the hyperparameters used to generate the results in the paper.)

**Comment by davidleon** [comment]
ah cool, found the code. but what's the mnist.rda? how to create one

**Comment by elbamos** [comment]
If you look in the vignette I've just added, there's code that downloads the mnist data and visualizes it.
