### ISSUE TITLE
Dimensionality reduction clumps all but one point together

### ISSUE THREAD

**Issue by spamcatcher345** [elbamos/largeVis#31]
Apologies for the cross-post, as this issue was reported here also:
https://github.com/lferry007/LargeVis/issues/8

Hoping to get some additional visibility.

<snip>

I have the same issue using Ubuntu 15.10. Has anyone solved this yet?

After running Largevis on my dataset, the first point is orders of magnitude larger than the remaining points after dimensionality reduction, resulting in a meaningless plot.

root@blah-VirtualBox:/home/blah/Desktop/LargeVis/20161012# ./LargeVis -input 1k_points.txt -output 1k_2d.txt
Reading input file 1k_points.txt ...... Done.
Total vertices : 1000 Dimension : 64
Normalizing ...... Done.
Running ANNOY ...... Done.
Running propagation 3/3
Test knn accuracy : 95.98%
Computing similarities ...... Done.
Fitting model Alpha: 0.000100 Progress: 99.993%
root@blah-VirtualBox:/home/blah/Desktop/LargeVis/20161012#

root@blah-VirtualBox:/home/blah/Desktop/LargeVis/20161012# head 1k_2d.txt
1000 2
-31.457289 -0.287726
12.466423 -0.287530
12.466411 -0.287530
12.466626 -0.287530
12.466501 -0.287530
12.466530 -0.287530
12.466509 -0.287530
12.466496 -0.287530
12.466705 -0.287530

Here is a link to the input data:
https://www.dropbox.com/s/bvup56przujg52d/1k_points.txt?dl=0

And a link to the Largevis output:
https://www.dropbox.com/s/jk2p0qof2sn7hr9/1k_2d.txt?dl=0

Any guidance would be greatly appreciated. Thank you!

</snip>

**Comment by elbamos** [comment]
I've responded in the other thread, so I'm closing this.  The issue appears to have been with your data file.  If anything else comes up, please reopen.  Thanks.

**Comment by spamcatcher345** [comment]
Replied on the other thread. Many thanks again.
