### ISSUE TITLE
how to use hdbscan?

### ISSUE THREAD

**Issue by zachmayer** [elbamos/largeVis#32]
I've having some trouble getting results from hdbscan.  A simple example on a small dataset would be helpful!

Thanks!

**Comment by elbamos** [comment]
Can you clarify where the issue is? It's a lot easier if you have an example. I can tell you, I'm simplifying the API for the next version, so you can just give it a largeVis object.

**Comment by zachmayer** [comment]
I'm just getting weird results.  I'll post some code later.

But an example of hdbscan I could just copy/paste from would probably let me figure it out.

Thanks!

**Comment by elbamos** [comment]
Zach - if your compiler is llvm, you can try the release candidate in the branch release/0.1.10.  (It may have compilation problems on some OS's, which is why it hasn't been released yet.)

**Comment by zachmayer** [comment]
Awesome!  I can probably figure that out.  Thanks!
