### ISSUE TITLE
mnist.Rda not included

### ISSUE THREAD

**Issue by rozyang** [elbamos/largeVis#33]
In Example 2, load("./mnist.Rda") does not work. At least the link of mnist.Rda should be given for downloading.

**Comment by elbamos** [comment]
I use this package https://cran.r-project.org/web/packages/neuralnet/index.html for mnist. The reason there's no link is that if I included the package in the example I'd have to list it as a dependency under cran's rules.

**Comment by elbamos** [comment]
I've added a note about this in the new version. Going to close this issue now. Please reopen if anything else comes up.

**Comment by rozyang** [comment]
Sorry, I still cannot get it work.

R version 3.3.2 (2016-10-31) -- "Sincere Pumpkin Patch"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

`>` library(deepnet)
`>` data<-load.mnist("/home/rozyang/work/data/mnist/hyphen")
`>` dim(data$train$x)
[1] 60000   784
`>` library(largeVis)
Loading required package: Matrix
largeVis was compiled with 32-bit types. This will limit the size of the datasets it can process. Consider recompiling with -DARMA_64BIT_WORD
`>` visObject <- largeVis(data$train$x, n_trees = 50, tree_th = 200, K = 50)

error: SpMat::SpMat(): invalid row or column index
Error in eval(substitute(expr), envir, enclos) : 
  SpMat::SpMat(): invalid row or column index
In addition: Warning message:
In largeVis(data$train$x, n_trees = 50, tree_th = 200, K = 50) :
  The Distances between some neighbors are large enough to cause the calculation of p_{j|i} to overflow. Scaling the distance vector.

**Comment by elbamos** [comment]
You have to actually transform the data - the steps are not shown in the example.

**Comment by rozyang** [comment]
Thanks. Now it works.
