### ISSUE TITLE
iris output is incorrect

### ISSUE THREAD

**Issue by rozyang** [elbamos/largeVis#34]
Using the lines in Example 1, the output gives no pattern at all. The IRIS data should be clustered.

**Comment by elbamos** [comment]
Are you using the version from cran?

**Comment by elbamos** [comment]
@rozyang Can you test the version that was uploaded to cran today?  Or from branch 0.1.10 here?

**Comment by elbamos** [comment]
@rozyang You haven't responded, so I'm going to close this.  Feel free to reopen.

**Comment by rozyang** [comment]
I guess the reason is sgd_batches = 10000 is not enough. Using sgd_batches = 1000000 or more makes it work.

**Comment by elbamos** [comment]
I'm still not sure precisely what version you're running and what you tried to do?

**Comment by rozyang** [comment]
I am using largeVis_0.1.10.2 from CRAN.
