### ISSUE TITLE
ubuntu 64

### ISSUE THREAD

**Issue by chupvl** [elbamos/largeVis#40]
Hello! I have tried to install from git and from the R-lib. In both cases got following error: "Error : object ‘opticsXi’ is not exported by 'namespace:dbscan'". System: ubuntu 16.04 (64bit).
What I am missing?

**Comment by elbamos** [comment]
A week ago the author of the dbscan package updated it and changed the name of the function. Thanks for letting me know. I'm surprised I didn't get a notification, I thought CRAN handled testing for this. Anyway I'll roll a fix into the next largeVis update, which is overdue anyway. For right now, I suggest using the prior version of dbscan.

**Comment by chupvl** [comment]
Many thanks! waiting for the fix and will test then.

**Comment by elbamos** [comment]
@chupvl Try the version in my develop branch, should be fixed now.

**Comment by elbamos** [comment]
@chupvl The updated version should be on cran now -- let me know if you have any issues.  I'm going to close this for now.
