### ISSUE TITLE
Error in newest R package version

### ISSUE THREAD

**Issue by rwarnung** [elbamos/largeVis#41]
Hi,
I get an error, when I load the package:

`> library(largeVis)`

> Loading required package: Matrix
> Error : object ‘opticsXi’ is not exported by 'namespace:dbscan'
> Error: package or namespace load failed for ‘largeVis’

my `sessionInfo()` is below.
When I google I find [this](http://r.789695.n4.nabble.com/Error-loading-largeVis-td4728831.html) - so somebody else has had this error too. They point to the CRAN page where this error apears too:
https://cran.r-project.org/web/checks/check_results_largeVis.html

Is there an issue with the newest version? Thank you!

> R version 3.3.1 (2016-06-21)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 7 x64 (build 7601) Service Pack 1
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
> [3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] Matrix_1.2-6
> 
> loaded via a namespace (and not attached):
> [1] tools_3.3.1     Rcpp_0.12.7     grid_3.3.1      dbscan_1.0-0    lattice_0.20-33

**Comment by elbamos** [comment]
One of the packages it depends on changes the name of a function last week. I'll be putting up a fix this week.

**Comment by elbamos** [comment]
@rwarnung @pablo14 try the version in my develop branch.

**Comment by rwarnung** [comment]
@elbamos works fine for me under windows. Thank you!

**Comment by pablo14** [comment]
Thanks @elbamos for the following up. It's not working in mac. 
Now the install.packages("largeVis") works, but when I do the library(largeVis) it throws the same error:

```
> library(largeVis)
Loading required package: Matrix
Error : object ‘opticsXi’ is not exported by 'namespace:dbscan'
Error: package or namespace load failed for ‘largeVis’
```
Here my session:

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.1
```

**Comment by elbamos** [comment]
If you're seeing that error message are you *sure* you're using the one from the development branch?

**Comment by pablo14** [comment]
That error appears when I try to install from CRAN:
```install.packages("largeVis")```
After your last comment, I tried to instal by:
```library(devtools)
install_github("elbamos/largeVis")
```

But it failed with other error. 

How can I install from the dev branch you mentioned?

**Comment by elbamos** [comment]
install_github("elbamos/largeVis", ref = "develop")

**Comment by pablo14** [comment]
Thanks!
Now it works, but I had one more problem:
```
ld: warning: directory not found for option '-L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [largeVis.so] Error 1
ERROR: compilation failed for package ‘largeVis’
```
This solves this problem: http://thecoatlessprofessor.com/programming/rcpp-rcpparmadillo-and-os-x-mavericks-lgfortran-and-lquadmath-error/

After this, I successfully tested some examples from the vignette.

**Comment by elbamos** [comment]
Looks like you haven't setup your compiler properly.

**Comment by pablo14** [comment]
I wrote a post that I'm close to publish and i mention this package, I'd like to avoid the readers regarding  the error message when they do ```install.packages("largeVis")```. Do you suggest I offer them to install the package by: ```install_github("elbamos/largeVis", ref = "develop")``` instead?

**Comment by elbamos** [comment]
Actually I'm prepping that as a release. I suggest installing from ref = "release/0.2", but it should be on CRAN in a few days.

Thanks, and I look forward to reading the post!

**Comment by pablo14** [comment]
Thanks for the support: http://blog.datascienceheroes.com/playing-with-dimensions-from-clustering-pca-t-sne-to-carl-sagan/

**Comment by pablo14** [comment]
Thanks for the support. The post: http://blog.datascienceheroes.com/playing-with-dimensions-from-clustering-pca-t-sne-to-carl-sagan/
