### ISSUE TITLE
as.dendogram.hbscan not found

### ISSUE THREAD

**Issue by gemcavoy** [elbamos/largeVis#47]
When running this example and others, R can't find the as. dendogram.hdbscan
> data(iris)
> vis <- largeVis(t(iris[,1:4]), K = 20, sgd_batches = 1)
> hdbscanobj <- hdbscan(vis, minPts = 10, K = 5)
> plot(as_dendrogram_hdbscan(hdbscanobj))

Error in plot(as_dendrogram_hdbscan(hdbscanobj)) : 
  could not find function "as_dendrogram_hdbscan"

**Comment by elbamos** [comment]
Thanks for reporting - its an error in the example. It's as.dendrogram.hdbscan instead of as_dendrogram_hdbscan.

**Comment by gemcavoy** [comment]
Thanks very much for your reply.

I actually tried it that way as well before I raised the issue and got the
same error. Tried it again just to confirm and still got the error.

data(iris)
vis <- largeVis(t(iris[,1:4]), K = 20, sgd_batches = 1)
hdbscanobj <- hdbscan(vis, minPts = 10, K = 5)
plot(as.dendrogram.hdbscan(hdbscanobj))

**Comment by gemcavoy** [comment]
Here's the session info if that's of use:

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.4

Matrix products: default
BLAS:
/System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK:
/Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] RCurl_1.95-4.8       bitops_1.0-6         largeVis_0.2
Matrix_1.2-9         Rcpp_0.12.10
[6] rstan_2.15.1         StanHeaders_2.15.0-1 ggplot2_2.2.1

loaded via a namespace (and not attached):
 [1] lattice_0.20-35  codetools_0.2-15 grid_3.4.0       plyr_1.8.4
gtable_0.2.0     stats4_3.4.0
 [7] scales_0.4.1     lazyeval_0.2.0   tools_3.4.0      munsell_0.4.3
 parallel_3.4.0   compiler_3.4.0
[13] inline_0.3.14    colorspace_1.3-2 gridExtra_2.2.1  tibble_1.3.0
>

**Comment by elbamos** [comment]
Because you should only have to call as.dendrogram -- it's an s3 function. That's why I changed it.

**Comment by elbamos** [comment]
@gemcavoy Can you confirm you're able to use it now?

**Comment by gemcavoy** [comment]
I was able to use it like this:
plot(as.dendrogram(hdbscanobj))


Also, just FYI.  I had to modify the example below (from the manual) to
transpose "dat" in order to get it to work (as your instructions suggest),
but the example in the manual doesn't use transpose.  Runs great with that
change.


library(largeVis)
# The aggregation dataset can be downloaded from
https://github.com/elbamos/clusteringdatasets
data(Aggregation)
dat <- as.matrix(Aggregation[, 1:2])
aggregateVis <- largeVis(t(dat), K = 10, tree_threshold = 100,
                         max_iter = 5, sgd_batches = 1)
clusters <- hdbscan(aggregateVis, verbose = FALSE)
gplot(clusters, dat)

**Comment by elbamos** [comment]
Yeah I totally failed to update the example. Sorry!

**Comment by elbamos** [comment]
fixed in 0.2.1 - please reopen if I'm mistaken, and thank you for the report!
