### ISSUE TITLE
"largeVis is incompatible with gcc < 4.9"

### ISSUE THREAD

**Issue by Asduveneck** [elbamos/largeVis#54]
I'm trying to run largeVis on R 3.4.1 when I encounter the above error. Do you happen to have an older version that is compatible with gcc < 4.9? I wish I could update the compiler, but it's from the company's network/grid-computer so I don't trust myself modifying that.

sessionInfo:
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server release 6.9 (Santiago)

EDIT: I don't mean to imply that this is an issue with largeVis itself. I just don't know how else to contact you which is why I decided to submit this as an issue.

**Comment by elbamos** [comment]
No, I’m sorry, it’s impossible - the code relies heavily on C++11.

**Comment by Asduveneck** [comment]
I understand. Thank you for getting back to me!
