### ISSUE TITLE
largeVis function's "threads" argument gives no control over number of threads

### ISSUE THREAD

**Issue by ghost** [elbamos/largeVis#55]
Apparently, at least for Windows, the _threads_ argument of the _largeVis_ operates the same way no matter to what it is set.  On my 4 core desktop, it always grabs all 4 cores to run, at least for a document-term matrix with 373 rows and 18000+ columns.  I am running with 50 GB of memory available to R.

**Comment by ghost** [comment]
I managed to get it to pay attention to threads=2 just fine.

**Comment by elbamos** [comment]
Let me know if the results worked well for you.
