### ISSUE TITLE
Error when installing largeVis on Ubunutu

### ISSUE THREAD

**Issue by jsaintvanne** [elbamos/largeVis#61]
Hi, 
I have this error when I try to install your package like this `install_github("elbamos/largeVis")` : 

```installing to /usr/local/lib/R/site-library/00LOCK-largeVis/00new/largeVis/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘largeVis’:
 .onAttach failed in attachNamespace() for 'largeVis', details:
  call: checkBits()
  error: la fonction 'enterRNGScope' n'existe pas dans le package 'Rcpp'
Erreur : le chargement a échoué
Exécution arrêtée
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/largeVis’
Erreur : Failed to install 'largeVis' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/RtmpptvoQp/file40d3768bc12b/largeVis_0.2.2.tar.gz’ had non-zero exit status
```

**Comment by elbamos** [comment]
Thanks, Julien. I’m working on a new version. Can you try installing from the develop branch and see if you still have the problem? Thanks.

**Comment by jsaintvanne** [comment]
It may be a bad question but how can I install from an other branch if you know that pliz ?
I found something to install from a release but not from a specific branch. I will test it immediatly when I have the right commandline. 

Thanks for your fast answer and good luck for your work

**Comment by jsaintvanne** [comment]
Ho just find the following command `install_github("elbamos/largeVis@develop")`

**Comment by jsaintvanne** [comment]
I obtain this error with develop branch 
```largeVis.cpp:35:8: error: declaration of ‘std::mutex Visualizer::mutex’ [-fpermissive]
  mutex mutex;
        ^~~~~
In file included from /usr/include/c++/8/mutex:43,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/armadillo:49,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloForward.h:49,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from largeVis.h:12,
                 from largeVis.cpp:1:
/usr/include/c++/8/bits/std_mutex.h:86:9: error: changes meaning of ‘mutex’ from ‘class std::mutex’ [-fpermissive]
   class mutex : private __mutex_base
         ^~~~~
make: *** [/usr/lib/R/etc/Makeconf:176: largeVis.o] Error 1
ERROR: compilation failed for package ‘largeVis’
* removing ‘/usr/local/lib/R/site-library/largeVis’
Erreur : Failed to install 'largeVis' from GitHub:
  (converti depuis l'avis) installation of package ‘/tmp/Rtmpwtcwc2/file483a37f1d0b5/largeVis_0.3.tar.gz’ had non-zero exit status
```

Thanks for your help

**EDIT**

It works when I install it from backoncran branch... Can I use it ?

**Comment by elbamos** [comment]
Hmm....   that’s really unexpected.  What compiler are you using? Can you try reinstalling Rccp, RccpArmadillo, and RccpParallel and then try largevis?

**Comment by elbamos** [comment]
You can definitely use the backoncran branch. 

I was also able to reproduce the issue you're seeing in the develop branch, which should have a fix later this week if not tonight.

**Comment by elbamos** [comment]
@jsaintvanne Can you try the version I have currently on the develop branch? It should resolve your issue.

**Comment by elbamos** [comment]
@jsaintvanne Just following-up about this... I've made some significant improvements recently, and would appreciate if you could let me know if your issue isn't resolved by what's currently up in develop. I'm going to close this in a few days if I don't hear from you.

**Comment by jsaintvanne** [comment]
Hello !
Sorry I can't answered before !
I think I now know why I had this issue : I'm on Ubuntu 18.10 and it is no longer maintain so I have a lot of problems with all packages...

**Comment by elbamos** [comment]
Ok. Please give the version in the develop branch a try and open a new issue if you still have trouble.
