### ISSUE TITLE
largeVis for R version 4.1.2

### ISSUE THREAD

**Issue by blosloos** [elbamos/largeVis#63]
Dear elbamos. 

Your largeVis algorithm and package has been of great help to us so far to reveal patterns in mass spectrometric data on environmental samples. Unfortunately, I am now forced to update from R version 3.3.3 to the latest version 4.1.2, and have thus tried to `install_github("elbamos/largeVis")`, using the devtools library, Rtools and its dependencies. On a 64bit Windows machine, this eventually leads to the following error (apart from a number of other warnings beforehand, e.g., on the RcppArmadillo package):

```
Error: package or namespace load failed for 'largeVis':
 .onAttach failed in attachNamespace() for 'largeVis', details:
  call: checkBits()
  error: function 'enterRNGScope' not provided by package 'Rcpp'
```

Do you have any idea how to solve this? Do you plan to update largeVis to later versions of R? Thanks & regards!

**Comment by elbamos** [comment]
Hi, try branch feature/backoncran. I really should get around to getting this actually back on CRAN…

**Comment by blosloos** [comment]
Great, thanks - that worked perfectly. Yes, maintaining CRAN packages can be time consuming ... but at least having a running version of your package on git is already awesome. largeVis is really helpful!
