### ISSUE TITLE
Compilation failed in Rstudio???

### ISSUE THREAD

**Issue by ww880412** [elbamos/largeVis#7]
When I use devtools install in Rstudio, It seems that compilation failed:

neighbors.cpp: In function ‘arma::mat searchTrees(const int&, const int&, const int&, const int&, const int&, const mat&, bool)’:
neighbors.cpp:114:25: error: ‘regspace’ is not a member of ‘arma’
     arma::vec indices = arma::regspacearma::vec(0, N - 1);
                         ^
neighbors.cpp:114:49: error: expected primary-expression before ‘>’ token
     arma::vec indices = arma::regspacearma::vec(0, N - 1);
                                                 ^
make: **\* [neighbors.o] Error 1
ERROR: compilation failed for package ‘largeVis’
- removing ‘/mnt/datascience/package/R/lib/R/library/largeVis’
  Error: Command failed (1)

**Comment by elbamos** [comment]
What version of RcppArmadillo do you have installed?  That's what provides the `arma::` functions.  I may need up add a version to the dependency.

**Comment by ww880412** [comment]
When I updated the RcppArmadillo to latest version, the error has been resolved~
(The previous version is 0.6.400)

**Comment by elbamos** [comment]
Ok, I will add a min version of RcppArmadillo in a bug patch shortly.  You may want to try the `bench` branch.

**Comment by elbamos** [comment]
I'm going to close this now.  Please reopen if the issue persists.
